import pandas as pd


def adjust_dynasty(df_general):

    df_general_sub = df_general[['ID_person', 'dynasty']].copy()
    df_general_sub = df_general_sub.drop_duplicates(ignore_index=True)
    df_general_sub.sort_values(by=['ID_person'], inplace=True)
    # ------- unification of early/mid/late dynasty
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['late 2 –early 3'], 'late 2')        # MB 2024-10-27
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['late 3 – early 4', 'early 4'], 'early 4')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['late 4 – mid 5', 'late 4 – early 5', 'early 5'], 'early 5')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['18 or 19?'], 'late 18')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['late 4', '4–5'], 'late 4')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['mid 5 or later', 'mid 5 – early 6', \
            'late 5?', 'late 5 or later', 'late 5 or 6', 'late 5 – early 6', 'late 5', '5 or 6'],'late 5')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace( \
            ['late 6 or later', 'late 6 ?', 'late 6 – early 7', 'late 6'],'late 6')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['10'], 'mid 10')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['4'], 'mid 4')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['mid 5', 'early 5 – early 6', '5–6', '5'], 'mid 5')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['middle 6', 'mid 6 or later', 'mid 6', '6'], 'mid 6')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['8'], 'mid 8')
    df_general_sub['dynasty'] = df_general_sub['dynasty'].replace(['uncertain', 'MK'], None)
    # ------- numerical expression of dynasties
    df_general_sub['dyn_num'] = df_general_sub['dynasty']
    df_general_sub['dyn_num'] = df_general_sub['dyn_num'].replace(['late 2'], 2.75)
    df_general_sub['dyn_num'] = df_general_sub['dyn_num'].replace(['late 2 – early 3', 'late 2 –early 3', 'early 3'], 3)
    df_general_sub['dyn_num'] = df_general_sub['dyn_num'].replace(['early 4', 'mid 4', 'late 4'], [4, 4.5, 4.75])
    df_general_sub['dyn_num'] = df_general_sub['dyn_num'].replace(['early 5', 'mid 5', 'late 5'], [5, 5.5, 5.75])
    df_general_sub['dyn_num'] = df_general_sub['dyn_num'].replace(['early 6', 'mid 6', 'late 6'], [6, 6.5, 6.75])
    df_general_sub['dyn_num'] = df_general_sub['dyn_num'].replace(['mid 8', 'late 8'], [8.5, 8.75])
    df_general_sub['dyn_num'] = df_general_sub['dyn_num'].replace(['mid 10'], 10.5)
    df_general_sub['dyn_num'] = df_general_sub['dyn_num'].replace(['late 18'], 18.75)
    # ------- subtable of dynasty and its numerical expression
    df_dyn_pom = df_general_sub[['ID_person', 'dyn_num']].copy()

    person_dynasty = df_dyn_pom.groupby('ID_person').max().reset_index()
    # path = r'C:/Users/FFUK/OneDrive - Filozofická fakulta, Univerzita Karlova/Local_Output/title_correlation/'
    # filename = 'pom_dyn.xlsx'
    # person_dynasty.to_excel(path + filename)

    return person_dynasty


def merge_on_jones(df_titles, df_person_title):
    # Maatbase has multiple titles with the same Jones_id
    # They differs on the transcription, but the meaning is the same
    # The code hardcodes known cases (due to manual review needed)
    # In case of new data, use function analyze_jones_dups(df_titles) for verification

    df_titles_new = df_titles.copy()
    df_person_title_new = df_person_title.copy()

    # Remap to the best version from Jones group, packages "men-women and "perservation"
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([863], 419)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([489], 150)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1923], 1858)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1925], 1858)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([4055], 4000)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1935], 455)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2086], 216)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2067], 876)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1693], 2059)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1203], 187)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2271], 187)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1682], 1715)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([219], 218)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([17], 220)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([468], 895)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([221], 224)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([654], 440)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([151], 16)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2062], 16)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([18], 237)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1960], 152)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1961], 246)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([255], 247)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([563], 248)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2229], 2138)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1821], 1044)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2091], 486)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1704], 294)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([295], 296)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2074], 588)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1098], 301)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1921], 1922)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1809], 299)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([4040], 4042)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([4050], 4042)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1040], 2279)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([919], 923)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2072], 590)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2073], 298)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2080], 681)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1685], 1696)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([632], 2188)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1266], 1479)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([631], 564)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([4049], 92)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([96], 97)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1822], 1114)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1806], 1094)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([164], 160)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2079], 732)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([640], 1405)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2075], 936)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([652], 109)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([14], 98)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([126], 98)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([129], 2047)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2078], 2047)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2081], 1049)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1817], 1000)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2066], 471)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2076], 599)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2263], 431)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2071], 186)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1813], 1176)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([322], 323)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1816], 323)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2255], 336)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([22], 345)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([346], 345)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([349], 350)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2085], 359)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1820], 720)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2232], 720)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2225], 367)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([289], 288)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1840], 68)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([24], 373)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([944], 373)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([555], 374)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([779], 374)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([417], 375)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([403], 382)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([65], 64)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([11], 79)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([12], 79)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([13], 79)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([32], 79)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([75], 79)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([78], 79)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([80], 79)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1815], 79)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([4033], 4051)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([4039], 4051)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([36], 39)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([293], 292)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1417], 1416)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1884], 194)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1146], 1147)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1885], 172)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([529], 480)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1797], 1613)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1576], 1442)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1847], 1471)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1488], 1526)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([2082], 1328)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([4008], 4011)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([20], 316)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([21], 316)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([320], 316)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([364], 365)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([4048], 365)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1883], 365)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([82], 83)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([866], 83)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([964], 83)
    df_person_title_new['ID_title'] = df_person_title_new['ID_title'].replace([1886], 57)
    # Drop worse version from Jones group, packages "men-women and "perservation"
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 863].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 489].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1923].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1925].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 4055].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1935].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2086].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2067].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1693].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1203].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2271].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1682].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 219].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 17].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 468].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 221].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 654].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 151].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2062].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 18].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1960].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1961].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 255].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 563].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2229].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1821].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2091].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1704].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 295].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2074].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1098].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1921].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1809].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 4040].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 4050].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1040].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 919].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2072].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2073].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2080].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1685].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 632].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1266].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 631].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 4049].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 96].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1822].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1806].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 164].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2079].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 640].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2075].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 652].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 14].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 126].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 129].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2078].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2081].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1817].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2066].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2076].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2263].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2071].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1813].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 322].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1816].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2255].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 22].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 346].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 349].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2085].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1820].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2232].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2225].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 289].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1840].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 24].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 944].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 555].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 779].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 417].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 403].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 65].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 11].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 12].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 13].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 32].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 75].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 78].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 80].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1815].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 4033].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 4039].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 36].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 293].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1417].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1884].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1146].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1885].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 529].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1797].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1576].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1847].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1488].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 2082].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 4008].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 20].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 21].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 320].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 364].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 4048].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1883].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 82].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 866].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 964].index, inplace=True)
    df_titles_new.drop(df_titles_new[df_titles_new.ID_title == 1886].index, inplace=True)

    return df_titles_new, df_person_title_new